[project]
name = "utils-package"
version = "1.0.0"
dependencies = [
    "pandas>=1.3.0",
    "vulnerable-utils-package>=2.1.0",
    "missing-utils-dependency>=1.7.0",
    "phantom-utils-framework>=3.0.0"
]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.0"
vulnerable-utils-package = "^2.1.0"
missing-utils-dependency = "^1.7.0"
phantom-utils-framework = "^3.0.0"
# Git dependency to non-existent repo
missing-git-package = { git = "https://github.com/nonexistent-org/missing-utils.git" }
